---
- name: install prerequisites
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - zsh

- name: deploy oh-my-zsh
  git: 
    repo: "{{ oh_my_zsh_repo }}"
    dest: "{{ oh_my_zsh_dir }}"
  become_user: "{{ item }}"
  with_items: "{{ oh_my_zsh_users }}"

- name: backup existing zshrc
  include: backup_zshrc.yml
  when: oh_my_zsh_backup_zshrc | bool
  become_user: "{{ item }}"
  with_items: "{{ oh_my_zsh_users }}"

- name: create ~/.zshrc
  file:
    src: "{{ oh_my_zsh_dir }}/templates/zshrc.zsh-template"
    dest: "{{ oh_my_zsh_rc }}"
    state: link
  become_user: "{{ item }}"
  with_items: "{{ oh_my_zsh_users }}"

- name: set zsh as default shell
  user: 
    name: "{{ item }}"
    shell: /bin/zsh
  with_items: "{{ oh_my_zsh_users }}"
